QWIKOSS-2 - [✨] When closing over values in `server$` the values should be marked as readonly
QwikDev/qwik pull request #5238
Opened 2023-09-28 19:42 UTC by gitstart

### What does this PR do?
This PR ensures that values serialized by server$() are immutable and triggers a clear error message if any mutation is attempted

### Issue reference
https://github.com/BuilderIO/qwik/issues/5019

### Demo video/scrennshot: 
https://www.loom.com/share/abc8b587001d4845bc55748000b0412f?sid=945d461e-79cc-4cd3-a80f-0e99bb0aa065
Happy hacking! 🎉

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

2023-10-04 21:52 UTC, mhevery commented
Love this change. Let me know when it is ready.

2023-10-05 06:07 UTC, wmertens requested changes
Can you also add an e2e spec that tries to change an object on the server? Something like

```js
server$(() => {
  try {
    myObject.deeper.foo = 'test'
    return false
  } catch (e) {
    if (/* some test that checks it errored because of freeze */)
      return true
    return false
  }
})
```

2023-10-05 06:07 UTC, wmertens commented on packages/qwik-city/runtime/src/server-functions.ts
>          return qrl.apply(requestEvent, args);
This is the only place where you should deep freeze the args. This is the code that runs on the server and the args are the ones sent by the client.

2023-10-18 10:28 UTC, gitstart commented
> Hi @gitstart thanks for your help, are you still on this PR or is it abandoned?

Sorry for the delay. we are still working on the issue

2023-10-18 14:46 UTC, wmertens commented
@gitstart could you rebase?

2023-11-22 14:15 UTC, wmertens commented on packages/qwik-city/runtime/src/server-functions.ts
> +            throw new Error('Cannot serialize instances of Node.');
Is this a good idea? Seems to me they are deliberately being ignored

2024-03-04 10:22 UTC, wmertens commented
@gitstart still interested in finishing this?

2024-05-10 22:34 UTC, PatrickJS commented
@wmertens @mhevery I'm changing this to only freeze in dev

2024-05-10 22:39 UTC, PatrickJS commented
in the future technically we can pass the current client value to the server then update the client signals from the server response

2024-05-10 22:48 UTC, merged