feat(server$): config argument
QwikDev/qwik pull request #6290
Opened 2024-05-09 21:32 UTC by PatrickJS

# Overview
fixes https://github.com/QwikDev/qwik/issues/5656

2024-05-10 05:39 UTC, PatrickJS commented
in another pr I can add 3 levels of config. I also want to do this for better AbortSignal

2024-05-10 07:10 UTC, DustinJSilk commented
This is awesome! 🤩

Would it make sense to have ServerError take a generic argument so any serializable data can be returned?

```tsx
export class ServerError<T = Record<any, any>> extends Error {
  constructor(
    public status: number,
    public data: T
  ) {
    super();
  }
}
```

2024-05-10 12:19 UTC, wmertens requested changes
Looking forward to this!

2024-05-10 12:19 UTC, wmertens commented on starters/apps/qwikcity-test/src/routes/(common)/server-func/server-configs/index.tsx
You also need a test for ServerError and the data passed

2024-05-10 13:01 UTC, wmertens commented
Misko is ok with this API extension

2024-05-10 18:25 UTC, PatrickJS commented on starters/apps/qwikcity-test/src/routes/(common)/server-func/server-configs/index.tsx
done

2024-05-10 18:29 UTC, PatrickJS commented
```ts
type ResponseTuple = [null | string, string];

const serverFunctionA = server$(async function a(): Promise<ResponseTuple> {
  throw new ServerError<[string]>(401, ["my error"]);
});

const serverFunctionB = server$(async function b(): Promise<ResponseTuple> {
  return [null, this.method || ""];
});

export const MultipleServerFunctionsInvokedInTask = component$(() => {
  const methodA = useSignal("");
  const methodB = useSignal("");

  useVisibleTask$(async () => {
    const [error /*, data */] = await serverFunctionA();
    if (error) {
      methodA.value = error;
    }
    await delay(1);
    //     err, method
    const [, method] = await serverFunctionB();
    methodB.value = method;
  });

  return (
    <div id="server-error">
      {methodA.value}
      {methodB.value}
    </div>
  );
});
```

2024-05-10 18:58 UTC, merged

2024-12-15 11:41 UTC, DustinJSilk commented
I'm curious why the error isn't thrown on the client so that it can be caught, and instead we return the error like the method was successful?

I'm wondering if this was the right decision for the given reasons:
- Does this go against usual JS conventions of catching errors rather than returning errors?
- Throwing an error and then not catching it later feels wrong - throwing should mean we catch
- We now have to handle both transient errors and ServerErrors - if the request fails we need to catch it, and if a ServerError is thrown we need to handle the value type.
- Changing code to throw ServerError instead of a native error means we have to update our code elsewhere to handle the new error response type, making it more of a breaking change

There is also actually a ErrorResponse class from a routeLoader$, which it might have made sense to reuse so that any API middleware, whether used in a server$ or routeLoader$, can throw the same class and result in the same status code/response handling.

I realise this might be late, but with the upcoming v2 changes, would it make sense to revisit this, or is there merit in the way it is currently handled?