docs: added an example for creating a dynamic Leaflet map
QwikDev/qwik pull request #6599
Opened 2024-06-25 10:24 UTC by gimonaa

Added an example of a Leaflet map component, a route, props, and JSON and GeoJSON files to create an initial reactive map.

# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2024-06-25 11:04 UTC, gioboa requested changes
Thanks @gimonaa for your improvement 
Can I ask you to use the CodeSandbox component to render your examples?
You can copy form the [Algolia page](https://github.com/QwikDev/qwik/blob/main/packages%2Fdocs%2Fsrc%2Froutes%2Fdocs%2Fcookbook%2Falgolia-search%2Findex.mdx)

2024-06-25 14:40 UTC, PatrickJS approved these changes

2024-06-25 14:42 UTC, PatrickJS commented
looks great. after you finish the Requested Changes we can get it in

2024-06-26 23:54 UTC, gioboa approved these changes

2024-06-27 11:33 UTC, merged