Update package.json
QwikDev/qwik pull request #6690
Opened 2024-07-16 03:07 UTC by ppusapati

# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2024-07-16 08:59 UTC, gioboa requested changes
Thanks for your contribution.
eslint changed the configuration with v9
https://eslint.org/docs/latest/use/migrate-to-9.0.0
I'm not sure that this bump will work fine 🤔
Did you test this change?

2024-08-01 08:09 UTC, gioboa commented
@ppusapati is it still valid or is it abandoned?

2024-08-01 12:17 UTC, ppusapati commented
Yes, have tested it and its still valid. 

"@builder.io/qwik": "^1.7.3",
 "eslint-plugin-qwik": "^1.7.3",
"eslint": "^9.8.0",

2024-10-06 19:09 UTC, wmertens requested changes

2024-10-06 19:09 UTC, wmertens commented on packages/eslint-plugin-qwik/package.json
> +    "eslint": "^9.7.0"
this will just force everyone to use v9 but it doesn't do anything to make us use v9

2024-10-13 06:48 UTC, wmertens commented
I'm going to close this, but feel free to open a new PR with eslint updated.

2024-10-13 06:48 UTC, closed without merging