fix: Remove Cannot resolve symbol from the integration tests in v2
QwikDev/qwik pull request #6737
Opened 2024-07-29 02:09 UTC by JerryWu1234

# Overview

https://github.com/orgs/QwikDev/projects/1/views/1?pane=issue&itemId=68407338

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2024-07-29 04:38 UTC, Varixo requested changes
This is not the correct fix. You shoudn't remove the error message from the code. Instead you need to find why this message is appearing and do something inside the tests

2024-07-29 06:48 UTC, JerryWu1234 commented
![image](https://github.com/user-attachments/assets/f85e0e34-1d71-4c14-a931-2ee8f68d1b03)

>This is not the correct fix. You shoudn't remove the error message from the code. Instead you need to find why this message is appearing and do something inside the tests

Sorry, I got it wrong.

I finish it now. I tweak the unit tests

2024-07-29 08:57 UTC, wmertens commented on packages/qwik/src/core/v2/tests/render-api.spec.tsx
> -  },
If you're moving everything into the default manifest, the countermanifest is no longer useful, so you should remove it.

I think it's fine to do it, the manifest may contain entries that aren't used.

2024-07-29 09:00 UTC, wmertens commented
Please fix the formatting. I recommend you enable format-on-save in your editor, with Prettier support enabled.

2024-07-30 09:44 UTC, wmertens approved these changes
![LGTM](http://i.imgur.com/GfJdZ2x.png)

2024-07-30 09:45 UTC, merged