add preserve modules to lib starter
QwikDev/qwik pull request #6773
Opened 2024-08-07 03:11 UTC by thejackshelton

# Overview

Adds preserve modules to the library starters. It also makes the entryname apparent in the build, otherwise you would have:
`index.qwik2.mjs` and so forth.

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2024-08-07 07:27 UTC, gioboa submitted a review, later dismissed
@thejackshelton yessss :+1:

2024-08-07 09:43 UTC, wmertens commented
Needs a changeset with why

2024-08-08 08:42 UTC, shairez requested changes
Like Wout said, this needs a changeset

2024-08-08 15:48 UTC, thejackshelton commented
Good catch will add one here soon

2024-08-13 18:21 UTC, shairez approved these changes

2024-08-13 18:21 UTC, merged