Update pages.json
QwikDev/qwik pull request #6776
Opened 2024-08-07 11:06 UTC by DevWeb13

Add learn-qwik.com

# Overview

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

# Use cases and why

- 1. One use case
- 2. Another use case

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] Added new tests to cover the fix / functionality

2024-08-07 11:55 UTC, gioboa requested changes
I tested the website with https://pagespeed.web.dev/ and we can't add this webiste because the score is too low 
![image](https://github.com/user-attachments/assets/3d97e00d-dff3-445f-a151-d34561dd81e2)
Can you try to fix it up?

2024-08-07 13:20 UTC, DevWeb13 commented
Oh shit lol!

I'm sorry.

It's mobile mode?

Ok i try fix it .

Thank you
________________________________
De : Giorgio Boa ***@***.***>
Envoyé : mercredi 7 août 2024 13:55
À : QwikDev/qwik ***@***.***>
Cc : LaRéponseDev ***@***.***>; Author ***@***.***>
Objet : Re: [QwikDev/qwik] Update pages.json (PR #6776)


@gioboa requested changes on this pull request.

I tested the website with https://pagespeed.web.dev/ and we can't add this webiste because the score is too low
image.png (view on web)<https://github.com/user-attachments/assets/3d97e00d-dff3-445f-a151-d34561dd81e2>
Can you try to fix it up?

—
Reply to this email directly, view it on GitHub<https://github.com/QwikDev/qwik/pull/6776#pullrequestreview-2224518201>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATOHMQ5G4YT3IXFP2ABIQ3DZQIDLRAVCNFSM6AAAAABMEFLRKOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMRUGUYTQMRQGE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-08-18 19:15 UTC, DevWeb13 commented
Hi ,

I think the performances are good from now on:
[cid:119fadaa-d185-4934-a626-c7139362fe22]
________________________________
De : Giorgio Boa ***@***.***>
Envoyé : mercredi 7 août 2024 13:55
À : QwikDev/qwik ***@***.***>
Cc : LaRéponseDev ***@***.***>; Author ***@***.***>
Objet : Re: [QwikDev/qwik] Update pages.json (PR #6776)


@gioboa requested changes on this pull request.

I tested the website with https://pagespeed.web.dev/ and we can't add this webiste because the score is too low
image.png (view on web)<https://github.com/user-attachments/assets/3d97e00d-dff3-445f-a151-d34561dd81e2>
Can you try to fix it up?

—
Reply to this email directly, view it on GitHub<https://github.com/QwikDev/qwik/pull/6776#pullrequestreview-2224518201>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATOHMQ5G4YT3IXFP2ABIQ3DZQIDLRAVCNFSM6AAAAABMEFLRKOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMRUGUYTQMRQGE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-08-18 19:17 UTC, DevWeb13 commented
________________________________
De : Loic Giuliano ***@***.***>
Envoyé : dimanche 18 août 2024 21:15
À : QwikDev/qwik ***@***.***>
Objet : RE: [QwikDev/qwik] Update pages.json (PR #6776)

Hi ,

I think the performances are good from now on:
[cid:119fadaa-d185-4934-a626-c7139362fe22]
________________________________
De : Giorgio Boa ***@***.***>
Envoyé : mercredi 7 août 2024 13:55
À : QwikDev/qwik ***@***.***>
Cc : LaRéponseDev ***@***.***>; Author ***@***.***>
Objet : Re: [QwikDev/qwik] Update pages.json (PR #6776)


@gioboa requested changes on this pull request.

I tested the website with https://pagespeed.web.dev/ and we can't add this webiste because the score is too low
image.png (view on web)<https://github.com/user-attachments/assets/3d97e00d-dff3-445f-a151-d34561dd81e2>
Can you try to fix it up?

—
Reply to this email directly, view it on GitHub<https://github.com/QwikDev/qwik/pull/6776#pullrequestreview-2224518201>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ATOHMQ5G4YT3IXFP2ABIQ3DZQIDLRAVCNFSM6AAAAABMEFLRKOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDEMRUGUYTQMRQGE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-08-18 19:18 UTC, DevWeb13 commented
Hi, 
I think the performances are good from now on:
![Capture d’écran du 2024-08-18 21-15-14](https://github.com/user-attachments/assets/e0c81976-93c2-450c-b050-9c5d28c51980)

2024-08-18 19:21 UTC, gioboa approved these changes
That's good to me.
![Screenshot_20240818-212006](https://github.com/user-attachments/assets/bc15e1ef-71b0-44a5-b85d-23499d11c511)
@DevWeb13

2024-08-18 19:25 UTC, merged

2024-08-19 08:04 UTC, DevWeb13 commented
I received this email, and I don't know what it means. Do I need to take any action on my end?
Thank you.

![Capture d’écran du 2024-08-19 10-01-15](https://github.com/user-attachments/assets/f83d8e6d-0f58-4e33-b673-7d5b0e4b25b7)
![Capture d’écran du 2024-08-19 10-01-30](https://github.com/user-attachments/assets/ca1c8229-7b02-416b-82ac-6729ca05e802)

2024-08-19 08:26 UTC, DevWeb13 commented
Ok thanks my friend.