add debugging section to docs issue #6836
QwikDev/qwik pull request #6857
Opened 2024-09-03 15:50 UTC by czuma

# What is it?

- [ ] Feature / enhancement
- [ ] Bug
- [x] Docs / tests / types / typos
- [ ] Infra

# Description

# Checklist:

- [ ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [ ] I have performed a self-review of my own code
- [ ] I have ran `pnpm change` and documented my changes
- [ x ] I have made corresponding changes to the Qwik docs
- [ ] Added new tests to cover the fix / functionality

2024-09-06 07:06 UTC, gioboa approved these changes
It looks good to me 👏 thanks @czuma

2024-09-08 13:23 UTC, wmertens requested changes
Nice, but isn't it easier to use `npx vite-bundle-visualizer`? Could even be a default script in the starter

2024-09-11 18:54 UTC, czuma commented
> Nice, but isn't it easier to use `npx vite-bundle-visualizer`? Could even be a default script in the starter

THAT'S GREAT! i tested and works amazing. Maybe we can split this in 2 parts, 1 is document this command instead of my PR, and 2nd part is to add to starter like you say. Let me work on that.

2024-10-13 06:51 UTC, wmertens commented
@czuma I think you can do both things in this PR. Looking forward to our new debugging sections in the docs! :smiley:

2025-04-02 19:56 UTC, maiieul commented
Closing as stale. Feel free to reopen a new one!

2025-04-02 19:56 UTC, closed without merging