Expose unwrapProxy as a low level API
QwikDev/qwik pull request #6960
Opened 2024-10-10 08:12 UTC by GrandSchtroumpf

# What is it?

- [x] Feature / enhancement
- [ ] Bug
- [ ] Docs / tests / types / typos
- [ ] Infra

# Description
`unwrapProxy` was marked as a @public API in JSDoc but wasn't exposed to the user.
Exposing `unwrapProxy` enables developer to clone the content of a `useStore()` using `structureClone` or IndexedDB

# Checklist:

- [x] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have ran `pnpm change` and documented my changes
- [x] I have made corresponding changes to the Qwik docs
- [ ] Added new tests to cover the fix / functionality

2024-10-12 11:33 UTC, wmertens requested changes
I'm ok with this change, but in v2 we're calling this `unwrapStore` which is a better name IMHO.

Can you change the export to `unwrapStore`?

2024-10-29 11:31 UTC, wmertens commented
@GrandSchtroumpf can you update the change set and API docs so they all say unwrapStore?

@shairez shall we put this in 1.9.2?

2024-10-29 13:02 UTC, GrandSchtroumpf commented
@wmertens I updated the changeset. The doc still refers to unwrapProxy because this is the original name of the function. I can change `unwrapProxy` to `unwrapStore` everywhere, but I don't want to create conflict with v2.

2024-10-29 22:25 UTC, shairez commented on .changeset/short-cycles-bake.md
> +Expose unwrapStore as a low level API
Please use the prefix `FEAT:` to indicate it's a feature

2024-10-29 22:25 UTC, shairez commented on .changeset/short-cycles-bake.md
> +'@builder.io/qwik': patch
Please change this to "minor" as it's adding a feature

2024-10-29 22:26 UTC, shairez commented
Thanks @GrandSchtroumpf !

Add a few short comments about the changesets
After that we can merge

@wmertens please resolve the "request changes" when you have a chance

2024-10-29 23:26 UTC, wmertens submitted a review, later dismissed

2024-10-29 23:53 UTC, shairez commented
nvm @GrandSchtroumpf 
I did the modifications on the changeset file because I wanted to merge asap to make this part of 1.9.2

But please read my review just as FYI for next time, thanks again for the PR! 🙏

2024-10-29 23:53 UTC, shairez approved these changes

2024-10-29 23:53 UTC, merged