docs: optimize expression in routeLoader$()
QwikDev/qwik pull request #7058
Opened 2024-11-11 05:14 UTC by JerryWu1234

# What is it?

- Feature / enhancement
- Bug
- Docs / tests / types / typos
- Infra

#6929 

# Description

# Checklist

- [ ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [ ] I performed a self-review of my own code
- [ ] I added a changeset with `pnpm change`
- [ ] I made corresponding changes to the Qwik docs
- [ ] I added new tests to cover the fix / functionality

2024-11-11 08:09 UTC, gioboa requested changes
Thanks @JerryWu1234 fro your help
is `**.**` a typo in your description?

2024-11-11 09:46 UTC, JerryWu1234 commented
> Thanks @JerryWu1234 fro your help is `**.**` a typo in your description?

done

2024-11-12 07:24 UTC, JerryWu1234 commented on packages/docs/src/routes/docs/(qwikcity)/route-loader/index.mdx
> +Please note that route loaders should be exported only from `layout.tsx` or `index.tsx` files. But they can be declared in any valid way ES modules allow. To reuse a route loader across multiple `lay
I'll try it

2024-11-14 03:02 UTC, gioboa approved these changes
Thanks @JerryWu1234

2024-11-14 03:03 UTC, merged