fix: standardise error handling
QwikDev/qwik pull request #7185
Opened 2024-12-20 14:51 UTC by DustinJSilk

# What is it?

- Bug

# Description

This fixes a few issues with server$ error handling

- 4xx ServerErrors are returning a a value instead of throwing an error on the frontend
- server$ middleware could not catch errors - the server$ function would simply exit early. https://github.com/QwikDev/qwik/issues/7183
- You can now also throw a ServerError in a routeLoader$ to change the status code and return some serialised data. This is simply an added bonus but should pave the way for more standardised errors across loaders, actions, and server$ functions

# Checklist

- [x] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [x] I performed a self-review of my own code
- [x] I added a changeset with `pnpm change`
- [x] I made corresponding changes to the Qwik docs
- [x] I added new tests to cover the fix / functionality

2024-12-20 14:53 UTC, DustinJSilk commented
I get this error when running pnpm change: `Failed to find where HEAD diverged from origin/upcoming. Does origin/upcoming exist?`

2024-12-20 14:54 UTC, DustinJSilk commented
I would add a fix for this: https://github.com/QwikDev/qwik/issues/7165, but i have no idea how to fix it.

2024-12-20 16:11 UTC, DustinJSilk commented
@wmertens fyi - returning errors as values was intentional in this PR: https://github.com/QwikDev/qwik/pull/6290.
I dont think this was the right decision, as it becomes really difficult to work with. Now, errors behave like javascript errors and the user can catch them and use a type guard on the data instead.

2024-12-23 10:50 UTC, DustinJSilk commented
@shairez any chance we can get this PR reviewed?

2025-01-01 06:54 UTC, wmertens commented
for the origin/upcoming, try `git fetch origin upcoming`.

So if I understand correctly, the only somewhat breaking change is that 4xx errors now throw on the client side, right? That seems more like a bugfix than a breaking change.

2025-01-05 13:34 UTC, DustinJSilk commented
Thanks @wmertens !

Yes, the only breaking change is that 4xx errors now throw on the client. It should be classified as a bug fix.

I've added a changeset now, I had to temporarily change the changset config `"baseBranch": "origin/upcoming",` to `"baseBranch": "upcoming",` to get it to work

2025-01-14 10:33 UTC, DustinJSilk commented on packages/qwik-city/src/middleware/request-handler/error-handler.ts
> -export class ErrorResponse extends Error {
Deprecate this, don't removfe

2025-01-14 10:33 UTC, DustinJSilk commented on packages/qwik-city/src/middleware/request-handler/user-response.ts
> -      console.error(e);
Try and find the logging class if it exists

2025-01-14 10:33 UTC, DustinJSilk commented on starters/apps/qwikcity-test/src/routes/(common)/server-func/server-error/index.tsx
> +const serverFunctionB = server$(async function b(): Promise<string> {
Add a test for routerLoader$ errors

2025-01-14 18:10 UTC, DustinJSilk commented on packages/qwik-city/src/middleware/request-handler/user-response.ts
> -      console.error(e);
There is no logger in Qwik City

2025-01-14 18:22 UTC, DustinJSilk commented on packages/qwik-city/src/middleware/request-handler/user-response.ts
> +        if (accept === '*/*') {
I wonder what the Accept header is for SSR vs CSR pages and if server$ functions should actually send an Accept of application/qwik-json?

2025-02-22 23:44 UTC, shairez submitted a review, later dismissed
great job Dustin!

2025-02-23 14:58 UTC, wmertens requested changes
Looks great, just two small things

2025-02-23 17:12 UTC, DustinJSilk commented
Thanks @wmertens and @shairez!

2025-02-27 14:24 UTC, DustinJSilk commented
Gentle nudge @wmertens

2025-03-04 13:41 UTC, wmertens approved these changes
![LGTM](https://i.imgur.com/TiV6Z6T.png)

2025-03-04 14:44 UTC, DustinJSilk commented
@shairez can you merge these changes please

2025-03-04 15:44 UTC, merged

2025-03-04 15:44 UTC, shairez commented
Thanks again @DustinJSilk ! great job!

2025-03-04 15:57 UTC, DustinJSilk commented
Thanks both!

2025-07-13 10:12 UTC, wmertens commented on packages/docs/src/routes/docs/(qwikcity)/error-handling/index.mdx
> +    (isDev && err instanceof Error && err.constructor.name === "RedirectMessage")
@DustinJSilk I visited that issue but I don't understand how it is related?

2025-07-13 10:24 UTC, DustinJSilk commented on packages/docs/src/routes/docs/(qwikcity)/error-handling/index.mdx
> +    (isDev && err instanceof Error && err.constructor.name === "RedirectMessage")
Vite makes a copy of dependencies in dev mode (in node_modules/vite i think).

This means there are 2 definitions of ServerError during dev: one exists in the Qwik code, and another gets copied into the Vite cache.

So when a ServerError is thrown, it's a Qwik ServerError instance, but when you import ServerError in the middleware, you're comparing it against the Vite cached ServerError which means instanceof doesn't work.