Update pages.json
QwikDev/qwik pull request #7218
Opened 2024-12-31 15:13 UTC by hypecode-tech

# What is it?

- Feature / enhancement
- Bug
- Docs / tests / types / typos
- Infra

# Description

# Checklist

- [ ] My code follows the [developer guidelines of this project](https://github.com/QwikDev/qwik/blob/main/CONTRIBUTING.md)
- [ ] I performed a self-review of my own code
- [ ] I added a changeset with `pnpm change`
- [ ] I made corresponding changes to the Qwik docs
- [ ] I added new tests to cover the fix / functionality

2024-12-31 15:53 UTC, gioboa requested changes
Nice, thanks @hypecode-tech 
Can you improve a bit the performance please?
![image](https://github.com/user-attachments/assets/1c6f18c6-015c-45aa-b1e2-b519c096e89a)

2025-03-15 07:28 UTC, wmertens commented
@hypecode-tech to be clear, the desktop performance is great, but the mobile performance suffers due to:
- large total size (5.6MB)
- images that can be optimized (1MB)

https://pagespeed.web.dev/analysis/https-dinkymetal-com/f45n7zsypy?hl=en&form_factor=mobile

once that's fixed we'd love to have you in the showcase!

2025-04-02 20:13 UTC, maiieul commented
closing as stale. Feel free to re-open a new one :)

2025-04-02 20:13 UTC, closed without merging

2025-04-03 00:04 UTC, hypecode-tech commented
![Ekran Görüntüsü 2025-04-03 03-04-02](https://github.com/user-attachments/assets/0a04a2c3-2226-47f1-b209-0370a8de1112)

We made some tweaks to enhance performance could you check again.